### ISSUE TITLE
导出“png”生成的大图片无法被编辑？

### ISSUE THREAD

**Issue by Magic-glass** [sum1re/caption_ocr_tool#14]
![图片](https://user-images.githubusercontent.com/49303407/93005579-db2eff80-f584-11ea-84da-cfcf86773d57.png)
实际上导出的是bmp格式？并且该文件无法拖进ps中切片（ocr限制图片大小，ps提示文件不能解析），使用画图虽然可以看，但是无法编辑或者另存为，会提示错误（不能储存）。
麻烦大佬了（鞠躬m(_ _)m）

**Comment by sum1re** [comment]
pre-α 版本之前使用 **PNG** 格式, α 版本以后更改为 **BMP** 格式, 但导出的文件名没有同步修改, 造成了 PS 无法读取的问题.

临时解决方法: 将文件后缀手动修改为 ***.bmp*** 

> 1. 修改后 PS 能正常读取/切图
> 2. 未修改时, Windows 10 LTSC 版本自带的画图程序可以读取/编辑/存储, 其他版本未测.

**Comment by Magic-glass** [comment]
昨天晚上已经尝试过修改后缀，ps依旧提示不能解析，Win7旗舰版以及Win10家庭版的画图都只能读取，不能编辑/另存为。
刚刚尝试sai2可以正常使用后缀修改为.bmp的文件，现在也算能用了，麻烦大佬了...
~~萌新感觉可能是图片格式的问题，与工具无关....吧...~~
