### ISSUE TITLE
目标图像必须是单通道图像[BUG]

### ISSUE THREAD

**Issue by SplitGemini** [sum1re/caption_ocr_tool#20]
**Describe the bug**
打开任意视频后开始都显示`目标图像必须是单通道图像`

**To Reproduce**
1. 打开任意视频
2. 点开始
3. 问题出现

**Expected behavior**
不知道这是不是正常的

**Screenshots**
![image](https://user-images.githubusercontent.com/34861918/106125902-ac15d500-6197-11eb-9b49-abbc0182cd79.png)

**Logs**
<details>
<summary><b>log</b></summary>
28-01-2021 16:59:38.116 ERROR 18160 --- [pool-2-thread-2] c.n.c.ocr.aspect.AopExceptionAspect      : Pointcut Class: com.neo.caption.ocr.service.impl.VideoServiceImpl
Pointcut Method: videoToCOCR
ExceptionName: com.neo.caption.ocr.exception.InvalidMatException
ExceptionMsg: alert.content.module.invalid_mat
ParamNames: [progressBar]
ParamClasses: [class javafx.scene.control.ProgressBar]
Values: [ProgressBar[id=progress_bar, styleClass=progress-bar]]
Full Stack: Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl	Method: videoToCOCR	Line: 115
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$FastClassBySpringCGLIB$$87498154	Method: invoke	Line: -1
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$EnhancerBySpringCGLIB$$1253b94f	Method: videoToCOCR	Line: -1
Declare: com.neo.caption.ocr.controller.BatController	Method: doVideoTask	Line: 227
Declare: com.neo.caption.ocr.controller.BatController$1	Method: call	Line: 168
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 24
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 13

28-01-2021 16:59:38.237 ERROR 18160 --- [pool-2-thread-2] c.n.c.ocr.aspect.AopExceptionAspect      : Pointcut Class: com.neo.caption.ocr.service.impl.VideoServiceImpl
Pointcut Method: videoToCOCR
ExceptionName: com.neo.caption.ocr.exception.InvalidMatException
ExceptionMsg: alert.content.module.invalid_mat
ParamNames: [progressBar]
ParamClasses: [class javafx.scene.control.ProgressBar]
Values: [ProgressBar[id=progress_bar, styleClass=progress-bar]]
Full Stack: Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl	Method: videoToCOCR	Line: 115
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$FastClassBySpringCGLIB$$87498154	Method: invoke	Line: -1
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$EnhancerBySpringCGLIB$$1253b94f	Method: videoToCOCR	Line: -1
Declare: com.neo.caption.ocr.controller.BatController	Method: doVideoTask	Line: 227
Declare: com.neo.caption.ocr.controller.BatController$1	Method: call	Line: 168
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 24
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 13

28-01-2021 17:25:14.745  INFO 12260 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Starting application on Lenovo with PID 12260 (D:\Program Files\Caption OCR Tool\app\cocr.jar started by GH in D:\Program Files\Caption OCR Tool\runtime\bin)
28-01-2021 17:25:14.781  INFO 12260 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
28-01-2021 17:25:24.793  INFO 12260 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Started application in 15.338 seconds (JVM running for 20.919)
28-01-2021 17:26:26.124 ERROR 12260 --- [pool-2-thread-3] c.n.c.ocr.aspect.AopExceptionAspect      : Pointcut Class: com.neo.caption.ocr.service.impl.VideoServiceImpl
Pointcut Method: videoToCOCR
ExceptionName: com.neo.caption.ocr.exception.InvalidMatException
ExceptionMsg: alert.content.module.invalid_mat
ParamNames: [progressBar]
ParamClasses: [class javafx.scene.control.ProgressBar]
Values: [ProgressBar[id=progress_bar, styleClass=progress-bar]]
Full Stack: Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl	Method: videoToCOCR	Line: 115
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$FastClassBySpringCGLIB$$87498154	Method: invoke	Line: -1
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$EnhancerBySpringCGLIB$$25e9066b	Method: videoToCOCR	Line: -1
Declare: com.neo.caption.ocr.controller.MainController$5	Method: call	Line: 433
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 24
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 13

28-01-2021 17:26:26.143  INFO 12260 --- [pool-2-thread-3] c.n.c.ocr.aspect.AopExceptionAspect      : com.neo.caption.ocr.service.impl.VideoServiceImpl - videoToCOCR in 450 ms
28-01-2021 17:26:33.826  INFO 12260 --- [pool-2-thread-4] c.n.c.ocr.aspect.AopExceptionAspect      : com.neo.caption.ocr.service.impl.OCRServiceImpl - apiInit in 1426 ms
28-01-2021 18:02:27.808 ERROR 12260 --- [pool-2-thread-5] c.n.c.ocr.aspect.AopExceptionAspect      : Pointcut Class: com.neo.caption.ocr.service.impl.FileServiceImpl
Pointcut Method: saveAss
ExceptionName: com.neo.caption.ocr.exception.InvalidMatNodesException
ExceptionMsg: MatNode list is null or empty.
ParamNames: [assFile]
ParamClasses: [class java.io.File]
Full Stack: Declare: com.neo.caption.ocr.service.impl.FileServiceImpl	Method: verify	Line: 396
Declare: com.neo.caption.ocr.service.impl.FileServiceImpl	Method: saveAss	Line: 107
Declare: com.neo.caption.ocr.service.impl.FileServiceImpl$$FastClassBySpringCGLIB$$f236f5bf	Method: invoke	Line: -1
Declare: com.neo.caption.ocr.service.impl.FileServiceImpl$$EnhancerBySpringCGLIB$$cebbfe8c	Method: saveAss	Line: -1
Declare: com.neo.caption.ocr.controller.MainController$2	Method: call	Line: 274
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 24
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 13

28-01-2021 18:02:27.809  INFO 12260 --- [pool-2-thread-5] c.n.c.ocr.aspect.AopExceptionAspect      : com.neo.caption.ocr.service.impl.FileServiceImpl - saveAss in 2 ms
28-01-2021 18:02:54.442 ERROR 12260 --- [pool-2-thread-3] c.n.c.ocr.aspect.AopExceptionAspect      : Pointcut Class: com.neo.caption.ocr.service.impl.VideoServiceImpl
Pointcut Method: videoToCOCR
ExceptionName: com.neo.caption.ocr.exception.InvalidMatException
ExceptionMsg: alert.content.module.invalid_mat
ParamNames: [progressBar]
ParamClasses: [class javafx.scene.control.ProgressBar]
Values: [ProgressBar[id=progress_bar, styleClass=progress-bar]]
Full Stack: Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl	Method: videoToCOCR	Line: 115
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$FastClassBySpringCGLIB$$87498154	Method: invoke	Line: -1
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$EnhancerBySpringCGLIB$$25e9066b	Method: videoToCOCR	Line: -1
Declare: com.neo.caption.ocr.controller.MainController$5	Method: call	Line: 433
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 24
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 13

28-01-2021 18:02:54.442  INFO 12260 --- [pool-2-thread-3] c.n.c.ocr.aspect.AopExceptionAspect      : com.neo.caption.ocr.service.impl.VideoServiceImpl - videoToCOCR in 315 ms
28-01-2021 18:35:06.262  INFO 6252 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Starting application on Lenovo with PID 6252 (D:\Program Files\Caption OCR Tool\app\cocr.jar started by GH in D:\Program Files\Caption OCR Tool\runtime\bin)
28-01-2021 18:35:06.267  INFO 6252 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
28-01-2021 18:35:09.059  INFO 6252 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Started application in 4.548 seconds (JVM running for 6.779)
28-01-2021 18:35:51.448 ERROR 6252 --- [pool-2-thread-3] c.n.c.ocr.aspect.AopExceptionAspect      : Pointcut Class: com.neo.caption.ocr.service.impl.VideoServiceImpl
Pointcut Method: videoToCOCR
ExceptionName: com.neo.caption.ocr.exception.InvalidMatException
ExceptionMsg: alert.content.module.invalid_mat
ParamNames: [progressBar]
ParamClasses: [class javafx.scene.control.ProgressBar]
Values: [ProgressBar[id=progress_bar, styleClass=progress-bar]]
Full Stack: Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl	Method: videoToCOCR	Line: 115
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$FastClassBySpringCGLIB$$87498154	Method: invoke	Line: -1
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$EnhancerBySpringCGLIB$$6941ff33	Method: videoToCOCR	Line: -1
Declare: com.neo.caption.ocr.controller.MainController$5	Method: call	Line: 433
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 24
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 13

28-01-2021 18:35:51.450  INFO 6252 --- [pool-2-thread-3] c.n.c.ocr.aspect.AopExceptionAspect      : com.neo.caption.ocr.service.impl.VideoServiceImpl - videoToCOCR in 738 ms
</details>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type: x64
 - Version 20H2

**Comment by John-Smith-2020** [comment]
@SplitGemini 请问你是怎么解决的？THX
