### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SplitGemini** [sum1re/caption_ocr_tool#22]
**Describe the bug**
批量处理时出错，但是重新打开后又可以

**To Reproduce**
1. 先处理一个视频并且OCR
2. 批量处理视频
3. See error

**Expected behavior**

**Screenshots**

**Logs**
cv::Exception: OpenCV(4.2.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\arithm.cpp:669: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type: x64
 - Version 20H2

**Additional context**

**Comment by sum1re** [comment]
无法复现错误, 把完整的 log 文件附上

**Comment by sum1re** [comment]
我无法复现错误.
在 设置-高级设置-日志-日志等级 调整为 DEBUG, 把复现错误后的完整的 log 文件附上

**Comment by SplitGemini** [comment]
> 我无法复现错误.
> 在 设置-高级设置-日志-日志等级 调整为 DEBUG, 把复现错误后的完整的 log 文件附上

我复现不出来了，但我发现新问题，批处理开始后未停止关闭窗口，进行其他操作（打开滤镜等）会崩溃。

**Comment by sum1re** [comment]
> > 我无法复现错误.
> > 在 设置-高级设置-日志-日志等级 调整为 DEBUG, 把复现错误后的完整的 log 文件附上
> 
> 我复现不出来了，但我发现新问题，批处理开始后未停止直接关闭窗口，然后进行其他操作（打开滤镜等）会崩溃。

这是后台线程没有正确关闭造成的, 将在下个版本中修复, 谢谢反馈
