### ISSUE TITLE
[已解决] [语言乱码] 界面、选项语言语言呈现乱码状态

### ISSUE THREAD

**Issue by Karanoyo** [sum1re/caption_ocr_tool#29]
![界面截图](https://user-images.githubusercontent.com/93567765/144677493-2076b31a-3e30-4fcb-8c27-65d1d1a056f7.png)

经过测试，这可能是属于我的系统的问题。
从笔记本上我了解到，程序本身毫无异常，因为没有乱码现象，一切显示正常。
可是，为什么偏偏在我的主用电脑上出现乱码问题（泪目 T  T，急用手抄工具呢）？
因为我不久前处理了50多G的字体包，可能在处理时不小心重复安装了一些字体。因此导致某个字体异常损坏（或是装了低版本缺字字体），刚好异常的字体就是这个手抄工具的界面、选项所使用的字体。

为什么会这样想呢？
其实，是因为安装程序时的安装界面里出现的文字并未出现乱码，进入程序后界面才显示乱码的。
这就纳闷了。还有就是，我目前也装了100多款程序，并没有发现有程序出现语言乱码的问题。
系统语言也修改过，无用。强烈怀疑是字体，请作者提供一下程序界面所使用字体的字体名称，让我测试一下我怀疑的方向对不对。
实在解决不了才来求助作者的。

**Comment by Karanoyo** [comment]
补充：无论安装为繁体还是英文都显示乱码（突然感觉不是字体问题了 T T，咋回事啊）
补充2：在虚拟机上安装也没有出现乱码。艾玛，不会要重装系统才能解决吧...
补充3：导入视频后，视频文件名中文部分也显示乱码

**Comment by sum1re** [comment]
1. 程序的所有样式都是由 *org.jfxtras.jmetro* 引入的未做任何修改, 其中字体设置为 `-fx-font-family: "Segoe UI";`
2. 安装程序和应用内语言没有关联, 默认值是操作系统的语言
3. 修改程序内语言的话, 用文本编辑器打开安装目录下的 `CreateShortcut.bar` 文件, 在 `ECHO Shortcut.Arguments = "-server` 后面插入 ` -Duser.language=xx -Duser.country=xx` (xx请用下表参数替代)

     |语言|user.language|user.country|
     |-|-|-|
     |简体中文|zh|CN|
     |繁体中文|zh|TW|
     |English|en|US|

**Comment by sum1re** [comment]
修改字体:
1. 下载 [Main.txt](https://github.com/sum1re/caption_ocr_tool/files/7653170/Main.txt) 并修改为 **`Main.css`**
2. 用压缩软件打开安装目录下的 `app/cocr.jar`, 把 **Main.css** 替换到 `BOOT-INF\classes\css` 里

由于我无法复现你的问题, 这个只能用来验证是不是字体导致的乱码

**Comment by Karanoyo** [comment]
> 修改字体:
> 
> 1. 下载 [Main.txt](https://github.com/sum1re/caption_ocr_tool/files/7653170/Main.txt) 并修改为 **`Main.css`**
> 2. 用压缩软件打开安装目录下的 `app/cocr.jar`, 把 **Main.css** 替换到 `BOOT-INF\classes\css` 里
> 
> 由于我无法复现你的问题, 这个只能用来验证是不是字体导致的乱码

非常感谢作者的帮助。
前面 1和3 条我没法尝试，原因是 CreateShortcut.bar 搜索不到，不知 -fx-font-family: "Segoe UI"; 填哪。

后面的修改字体的操作，很顺利。
就是，问题依旧。
现在，我感觉与字体无关，就是我的操作系统出了些毛病罢了（还找不出源头）。
不过，我也想了一个不用重装系统的妙法。O(∩_∩)O哈哈~，就是弄一个双系统。
（老早就想做了，作为系统哪天故障进不去的备用手段）

谢谢作者了。
先补个觉。bye~

**Comment by Karanoyo** [comment]
天啦撸，我昨晚做了个梦，是关于Caption OCR Tool的，神奇的梦
梦的内容是：Caption OCR Tool启动后，字体慢慢的恢复正常了（从乱码转为可读）

一睡醒我就紧张地唤醒电脑，打开Caption OCR Tool
简直不敢相信，眼前的Caption OCR Tool界面是正常的，没有乱码

但是，奇迹是不存在的。
我不断的回忆之前的操作，有关字体的操作，寻找恢复正常的原因。
1、删除所有用户字体
2、覆盖“为所有用户”安装过的字体
3、安装双系统，体验了win11（应该无关）
反正，就是字体的锅没错了（我想）

开心的早晨呀，作者早上好啊
bye~

![Snipaste_2021-12-07_07-53-25](https://user-images.githubusercontent.com/93567765/144941948-620e3859-8ab4-46bb-ab7c-e20321c2e9e3.png)
