### ISSUE TITLE
Win10 64位下报错

### ISSUE THREAD

**Issue by panxinyang2014** [sum1re/caption_ocr_tool#9]
操作系统：Win10 64位
程序版本：0.0.2-beta
错误信息如下：
06-06-2020 10:31:47.577 ERROR 1648 --- [pool-2-thread-3] c.n.c.ocr.aspect.AopExceptionAspect      : Pointcut Class: com.neo.caption.ocr.service.impl.VideoServiceImpl
Pointcut Method: videoToCOCR
ExceptionName: org.opencv.core.CvException
ExceptionMsg: cv::Exception: OpenCV(4.2.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\count_non_zero.dispatch.cpp:124: error: (-215:Assertion failed) cn == 1 in function 'cv::countNonZero'

ParamNames: [progressBar]
ParamClasses: [class javafx.scene.control.ProgressBar]
Values: [ProgressBar[id=progress_bar, styleClass=progress-bar]]
Full Stack: Declare: com.neo.caption.ocr.service.impl.OpenCVServiceImpl	Method: countBlackPixel	Line: 311
Declare: com.neo.caption.ocr.service.impl.OpenCVServiceImpl$$FastClassBySpringCGLIB$$c7a12de	Method: invoke	Line: -1
Declare: com.neo.caption.ocr.service.impl.OpenCVServiceImpl$$EnhancerBySpringCGLIB$$b4470b85	Method: countBlackPixel	Line: -1
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl	Method: videoToCOCR	Line: 113
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$FastClassBySpringCGLIB$$87498154	Method: invoke	Line: -1
Declare: com.neo.caption.ocr.service.impl.VideoServiceImpl$$EnhancerBySpringCGLIB$$bc7b10a7	Method: videoToCOCR	Line: -1
Declare: com.neo.caption.ocr.controller.MainController$5	Method: call	Line: 434
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 24
Declare: com.neo.caption.ocr.util.AsyncTask	Method: call	Line: 13

**Comment by sum1re** [comment]
此问题不属于程序问题, 调整你的滤镜配置
